### PR TITLE
Update of DeepTauID to ver. 2017v2 (backport to 10_2_X)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR updates DeepTauID to version 2017v2. The new version, thanks to revised structure of used DNN, fixes issues of version 2017v1 that is a size of training files and memory consumption are greatly reduced. Possibility to run previous version is maintained.

This is backport of #26796 to 10_2_X **without** DeepTauID in the standard MiniAOD workflow.

Details on DeepTauID performance in the original PR

**Note:** This PR requires datafiles from cms-data/RecoTauTag-TrainingFiles#3 although it is not necessary for official workflows and standard tests.

#### PR validation:

As the PR does not include anything to official workflows it was validated with a simple standalone test using `RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py` which requires datafiles in cms-data/RecoTauTag-TrainingFiles#3. Unit-tests should not show any differences.
 

#### if this PR is a backport please specify the original PR:

This is backport of #26796 to 10_2_X (prepared on top of 10_2_15)

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@mbluj, this backport differs from #26796 because of the usage in ```RecoTauTag/RecoTau/plugins/DeepTauId.cc``` of the ```TauIdMVAAuxiliaries clusterVariables```, which were still used as accessors in 10_2_X, but they were outdated since then. The difference is minimal, and rather trivial indeed, but still...

Since in this PR the inclusion in the miniAOD was not backported, as it was decided in order not to generate differences with the already produced miniAOD in 10_2_X, tests correctly do not show differences in output.

Just to be sure that everything works and there will be no need of last minute fixes, please confirm that this PR was tested as such standalone in 10_2, and that its results look as expected.

**Comment by mbluj** [comment]
> @mbluj, this backport differs from #26796 because of the usage in `RecoTauTag/RecoTau/plugins/DeepTauId.cc` of the `TauIdMVAAuxiliaries clusterVariables`, which were still used as accessors in 10_2_X, but they were outdated since then. The difference is minimal, and rather trivial indeed, but still...

Yes indeed there is a purely technical difference due to refactoring of tauID helper class to set of standalone functions in #24382 (merged to 10_3_X) - sorry for not mentioning this difference.

> 
> Since in this PR the inclusion in the miniAOD was not backported, as it was decided in order not to generate differences with the already produced miniAOD in 10_2_X, tests correctly do not show differences in output.

We preformed such checks and observe small differences at event-by-event basis, so we try to understand what is a source of the differences. It is unlikely caused by the refactoring in #24382 as other tauIDs are not affected by this at all.
> 
> Just to be sure that everything works and there will be no need of last minute fixes, please confirm that this PR was tested as such standalone in 10_2, and that its results look as expected.

This PR requires also modification of cms-dist as in cms-data/RecoTauTag-TrainingFiles#3 to include training files.

**Comment by perrotta** [comment]
> We preformed such checks and observe small differences at event-by-event basis, so we try to understand what is a source of the differences. It is unlikely caused by the refactoring in #24382 as other tauIDs are not affected by this at all.

Thank you @mbluj : please report here as soon as you get any conclusion from your checks

**Comment by mbluj** [comment]
The issue is understood: the difference is related with redefinition of `pat::PackedCandidate::hcalFraction()` introduced in #26506 (>=CMSSW_10_6_X). To remove the difference DeepTau in 106X and master should be modified as `RecoBTag/FeatureTools/plugins/DeepBoostedJetTagInfoProducer.cc` #L305-312 in #26506. 
Therefore, I propose that I will prepare fix to master and modify #27146 (for UL/10_6_X) before it is merged - is it fine?

**Comment by perrotta** [comment]
> The issue is understood: the difference is related to redefinition of `pat::PackedCandidate::hcalFraction()` introduced in #26506 (for >=CMSSW_10_6_X). To remove the difference DeepTau in 106X and master should be modified as `RecoBTag/FeatureTools/plugins/DeepBoostedJetTagInfoProducer.cc` #L305-312 in #26506. Therefore, I propose that I will prepare a fix PR to master and modify #27146 (for UL/10_6_X) before it is merged - is it fine?

Just to understand: what you mean is that, given the changes integrated with #26506, the DeepTau ID is now "bugged" in releases >= 10_6, and the fix will be similar to https://github.com/cms-sw/cmssw/pull/26506/files#diff-f8b8043883b1ffc9129c25224175ff91R306? 

If so yes, please provide the fix for both the master and the UL release versions of this PR.
10_2 is therefore the "correct" one against which you will compare the effectiveness of the fix.

**Comment by mbluj** [comment]
> > The issue is understood: the difference is related to redefinition of `pat::PackedCandidate::hcalFraction()` introduced in #26506 (for >=CMSSW_10_6_X). To remove the difference DeepTau in 106X and master should be modified as `RecoBTag/FeatureTools/plugins/DeepBoostedJetTagInfoProducer.cc` #L305-312 in #26506. Therefore, I propose that I will prepare a fix PR to master and modify #27146 (for UL/10_6_X) before it is merged - is it fine?
> 
> Just to understand: what you mean is that, given the changes integrated with #26506, the DeepTau ID is now "bugged" in releases >= 10_6, and the fix will be similar to https://github.com/cms-sw/cmssw/pull/26506/files#diff-f8b8043883b1ffc9129c25224175ff91R306?
Yes, it unfortunately is bugged in the sense that it was trained with 94X samples produced before redefinition of hcalFraction... And yes, the fix will be similar as quoted above.

> 
> If so yes, please provide the fix for both the master and the UL release versions of this PR.
> 10_2 is therefore the "correct" one against which you will compare the effectiveness of the fix.
OK, will prepare them soon.

**Comment by perrotta** [comment]
+1
- Backport of #26796, excluding the part which updates the default miniAOD production sequence: only the code is made available for it.
- Jenkins tests pass and show no differences, as expected
- It needs a cmsdist pull request based on cms-data/RecoTauTag-TrainingFiles#3 in order to be able to run the ID in 10_2

**Comment by civanch** [comment]
+1

**Comment by mbluj** [comment]
Recent commit replaces `std::isnan` (which does not work when fast-math is used) by `edm::isNotFinite` as suggested by the static analyzer.

**This commit is backported from** #27173

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of #26796 and #27173

**Comment by perrotta** [comment]
In the (previous version of the) tests there was a failing comparison for the HLT DQM histo hltEle15Ele8CaloIdLTrackIdLIsoVLEtLeg1Filter_gsfEle_passFilter_HLTphi_eb for wf 136.85 RunEGamma2018A, see https://github.com/cms-sw/cmssw/pull/27148#issuecomment-499973344: this looks completely un-related to me, still maybe worth being looked at by DQM in order to understand the reason for such a non-reproducibility (attn @andrius-k, @kmaeshima, @schneiml, @jfernan2, @fioriNTU)

Let see if it reproduces in the tests currently ongoing...

**Comment by jfernan2** [comment]
@perrotta I guess you mean this:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2019-06-11-2300+faedbf/32210/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM/HLT_EGM_Source_Histos_hltEle15Ele8CaloIdLTrackIdLIsoVLEtLeg1Filter.html

Looking at the code changes and since there are no additional commits on top of the comparison, the change is tiny but clearly un-related... I don't have an explanation, number of entries are the same... where is the missing entry? Overflow or underflow?

**Comment by perrotta** [comment]
> Looking at the code changes and since there are no additional commits on top of the comparison, the change is tiny but clearly un-related... I don't have an explanation, number of entries are the same... where is the missing entry? Overflow or underflow?

Yes, I don't expect that such a change in the DQM plot has anything to do with this PR, I only pointed it to you in case you want to inspect it.
By the way, also in the latest test results, see https://github.com/cms-sw/cmssw/pull/27148#issuecomment-501351833, the same DQM plot ends up with the same difference

**Comment by perrotta** [comment]
+1
- Changes since last reco signature in https://github.com/cms-sw/cmssw/pull/27148#issuecomment-500870042 only deal with the inclusion of a minor fix to silence the static analyzer (also included in the master version of this PR) with no effect on outputs
- Jenkins tests pass and show no differences, as expected because the new ID is not propagated to the miniAOD production sequence in this 10_2_X backport

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1
