### PR TITLE
SiPM nonlinearity, parameters from CondDB, update tau, cleanup

### PR DESCRIPTION
**Pull request by kpedro88**
This PR supersedes #16070 (which should be closed). One of the issues under discussion for that PR, HO SiPM parameters in the database, has already been resolved. To recap: in #15058, when the new features were added to the SiPM simulation for HE, we propagated the same parameter values to HO (but only for Run 1). There was then a bit of confusion when transferring those parameters to the database. Upon reflection, we decided these new features should be avoided for HO entirely, since they have not been tuned for it. This resets the Run 1 HO sim back to how it was before 810pre9, and the Run 2 HO sim should be unchanged now that the database conditions are fixed.

After several weeks of internal discussions, a few decisions were made about the nonlinearity implementation. The SiPM simulation already includes nonlinearity using a saturation/recovery model for pixels with recovery time constant tau. Therefore, it would be redundant to include the saturation/recovery model _and_ apply the inverted nonlinearity correction (derived from bench data) in the simulation. For now, we have decided to stick with the saturation/recovery model. However, the code to invert the nonlinearity correction is left in place, in case of future studies.

This implies a few things:
1) The nonlinearity correction from MC needs to be derived from the SiPM simulation. A tool has been added for this: `SimCalorimetry/HcalSimAlgos/test/sipmnonlinearityanalyzer_cfg.py`.
2) The value for tau has been updated to 10 ns, based on a recommendation from experts. This significantly improves the agreement of the simulated nonlinearity with the bench data: [slides](https://indico.cern.ch/event/578882/contributions/2345268/attachments/1358769/2056434/sipm_simulation_nonlinearity.pdf)
3) Tau is now a configurable python parameter, and left as 5ns for HO to avoid unnecessary changes to that simulation (since the HO signals tend to be small, the nonlinear effect is also small and generally neglected).
4) The new nonlinearity parameters have been updated in the hardcode conditions. This PR now activates the reco application of the nonlinearity correction (since #16197 from @igv4321 is already merged), so the corrections in the database need to be updated to give the most appropriate results. @abdoulline is working on this. In the meantime, to pick up the hardcode condition values:

```
from SLHCUpgradeSimulations.Configuration.HCalCustoms import load_HcalHardcode
process = load_HcalHardcode(process)
process.es_hardcode.toGet = cms.untracked.vstring("GainWidths","SiPMCharacteristics")
```

@mariadalfonso is checking the effect of the nonlinearity correction on M2 performance (hopefully it should provide some improvement at high energy).

In addition, I checked off a few other items on my todo list for the SiPM code:
5) remove `iConfig.exists()` from `HcalSimParameters` (recall this contributed to the bug/digression fixed in #15834).
6) Restore the use of `doSiPMSmearing` for HO (only for 2017 and beyond, leaving the old versions as they were) with the old pulse shape (suitable for HO SiPMs). This required adding `HcalMCParams` to `HcalDbService` to get access to the pulse shape number on a per-channel basis.
7) Remove some unused fragments in the SiPM code that had been lying around.

Note: there may be a separate PR in the near future updating some SiPM parameters, as we have been notified that the TB data used to measure the parameters was taken at V-VB = 4.4 V, while the SiPMs installed in HE will be operated at V-VB = 3 V. However, some data still needs to be analyzed for this, and it should be totally orthogonal to this PR.

The other item still coming is ZS thresholds for HE (from @lihux25), but these of course depend on any parameter changes.

@civanch, @slava77: I would appreciate a rapid review of this PR if possible. I know it has a long description, but most of the new changes are rather minor. (Also, the majority of added lines are in the new standalone tool to measure the simulated nonlinearity.)

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@smuzaffar this PR is having the issue where comparisons still say running even though the bot reports they're available, can you take a look?

**Comment by slava77** [comment]
@kpedro88 if appropriate calibration payloads should be in GT for testing this PR, the autoGT change should be a part of this PR

**Comment by slava77** [comment]
@kpedro88 please provide some basic plots of performance.
Ideally eReco / eGen vs eGen for HCAL hits or at least some proxies like M2/M0, jet reco/gen from DQM.
IMO, all non-technical PRs should come with this for self-documentation.

**Comment by kpedro88** [comment]
@mariadalfonso is working on tests of the M2 performance.

We can update autocond in this PR once the new records are inserted (@abdoulline is working on it), but this might conflict with #16301.

**Comment by abdoulline** [comment]
I've responded via e-mail, but I don't see the message arrived there in PR thread, and the same (absence of comment sent via e-mail) happened yesterday with my rather long comment in another PR thread (#16150 RPD implementation)

So I'm copy-pasting:

"The appropriate tag HcalSiPMCharacteristics_2017_v5.0_mc  has been submitted. Alas... now we need to bug Marco @mmusich  again..."

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@kpedro88 

> We can update autocond in this PR once the new records are inserted (@abdoulline is working on it), but this might conflict with #16301.

the conflict is no obstacle since #16301 is currently incomplete (as also not working), I'll just rebase once we are done here.

@abdoulline 

> "The appropriate tag HcalSiPMCharacteristics_2017_v5.0_mc has been submitted. Alas... now we need to bug Marco @mmusich again..." 

the [request from Walter ](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2702.html) has been received. Working on that now.

**Comment by mmusich** [comment]
@kpedro88 
https://github.com/cms-sw/cmssw/pull/16326 contains the updated conditions.

**Comment by civanch** [comment]
@kpedro88 , now much more differences than in previous PR #16070

**Comment by kpedro88** [comment]
@civanch changes are expected from this PR in Run1 MC and 2017 workflows, which is consistent with what the comparison shows.

As explained previously, in an earlier PR we enabled new features/parameters in the SiPM simulation for Run1 HO (without fully thinking it through). We have now returned the Run1 HO simulation to its previous state. Because the SiPM simulation makes several random number calls, any change here leads to changes in the random number chain elsewhere.

The 2017 changes are, of course, the primary intent of this PR.

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
@kpedro88 will this PR need any changes to pick up payloads provided in #16326 ?

**Comment by kpedro88** [comment]
@slava77 the new values (from simulation instead of bench data, for self-consistency) should get picked up automatically once that PR is merged.

**Comment by slava77** [comment]
@cmsbuild please test
... I'm getting a compilation error in pre15.

**Comment by kpedro88** [comment]
@slava77 I understand the cause of this error, it's an implicit conflict with #16302. I'll rebase and fix it.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
The appropriate tag HcalSiPMCharacteristics_2017_v5.0_mc  has been submitted. Alas... now we need to bug Marco again...


________________________________

**Comment by mmusich** [comment]
@abdoulline `HcalSiPMCharacteristics_2017_v5.0_mc` is already part of the GT via https://github.com/cms-sw/cmssw/pull/16326 are we talking about version 6.0?

**Comment by kpedro88** [comment]
@mmusich github just spat out a bunch of email replies that were sent over the past few days and got stuck in a server somewhere

**Comment by mmusich** [comment]
Ah maybe some leftover of the DDos attack of last week... Thanks

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
as Kevin has already mentioned all those old comments sent via e-mail 
several days ago are now arriving as "recent" in many PRs threads...

**Comment by kpedro88** [comment]
curse you DAS

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Comparisons show expected differences in Run1 MC, 2017 MC, and 2023D3 MC.

https://github.com/cms-sw/cmssw/pull/15959#issuecomment-256327869 shows M2 vs M0 with this PR and #15959. In general, the changes are small. This PR increases the simulated nonlinearity (to better match data) as well as activating the nonlinearity correction, so some additional minor variance in response is expected.

@civanch @slava77 @mmusich @ggovi please sign if possible...

File: SimCalorimetry/HcalSimProducers/python/hcalSimParameters_cfi.py [hunk 1]
```diff
@@ -120,10 +124,14 @@
...
-        sipmDarkCurrentuA = cms.double(0.055),
-        sipmCrossTalk = cms.double(0.32),
         doSiPMSmearing = cms.bool(True),
+        sipmTau = cms.double(10.),
+    )
+)
+from Configuration.Eras.Modifier_run2_HCAL_2017_cff import run2_HCAL_2017
+run2_HCAL_2017.toModify( hcalSimParameters,
+    ho = dict(
+        doSiPMSmearing = cms.bool(True)
```
Comment (slava77) [inline SimCalorimetry/HcalSimProducers/python/hcalSimParameters_cfi.py]: HO did not change in 2016 vs 2017, right?
IMO, it makes more sense to have the same configuration for the same detector setup for consistency.

Comment (slava77) [inline SimCalorimetry/HcalSimProducers/python/hcalSimParameters_cfi.py]: Well, if it's a bug or even an improvement to simulation to match data better, it better be fixed.
I would only prefer that all Run2/Run1 performance changes are factorized in a separate PR.
Run2 <2016 is still not affected by this PR.

Comment (kpedro88) [inline SimCalorimetry/HcalSimProducers/python/hcalSimParameters_cfi.py]: I can make a separate followup PR to propagate this change back to Run2/1 MC.

**Comment by slava77** [comment]
[all plots below with "this PR" are #16315 + #16326 ]


Run-1 changes are driven by HO
ttbar wf 202
all_sign788vsorig_ttbarpuwf202p0c_log10horechitssorted_horeco__reco_obj_obj_energy3

or SingleMu pt1000 to have some more real HO energy
all_sign788vsorig_singlemupt1000wf22p0c_log10horechitssorted_horeco__reco_obj_obj_energy3

In 2017 setup there is a pretty large increase in the hit yield across the spectrum:
Pi 5 to 5 TeV sample:
all_sign788-2017vsorig-2017_pie5to5000in2017c_log10recopfclusters_particleflowclusterho__reco_obj_energy
we are getting about 250 clusters per event for just two generated pions and and rarely a single one reaching HO.
- is it a combination of dark current settings with cross-talk or just cross-talk?

Here is an overlay with a doubleEG plot from data 274199 (normalized to the same number of processed events)
wfpie5to5000in2017vsdata_origvssign788_pfclu_ho_log10e
- here you can see that new MC with thisPR has features that do not represent data both at low and high energy
    - repeated values of energy in spikes do not appear to correspond to the MC pions be anywhere close to the HO acceptance
    - hits below 1 GeV exceed what we expect from data by more than an order of magnitude.

- CaloJets are protected against this HO issue because towerMaker ignores HO
- PF candidates are partially protected because PFAlgo ignores single HO clusters: particle guns have only rare fakes, but the higher PU events have pretty significant rate with wrong energy due to HO.

HE looks reasonably OK.

At face value, this is a no-go due to HO.
But maybe I'm missing something.

**Comment by kpedro88** [comment]
Dark current and crosstalk are now disabled for HO with the conditions from #16326.

For Run1 HO MC, it would be better to compare to 8_1_0_pre8. One goal of this PR is to reset the HO MC back to that state (more or less). I think your first two plots make sense; they're showing the removal of extra photoelectrons from dark current, which show up somewhere between pedestal noise and signal.

For 2017 HO MC, it looks like `doSiPMSmearing` is causing problems. My preference would be to disable it for now if that would help get this PR approved. The realism of HO MC is of much lower importance than HE right now.

**Comment by slava77** [comment]
[github ate my email again]

Run1 HO is sensible, as you describe.

The 2017 HO is nonsense.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
So, the spikes at high energy are gone
what about the huge bump below E=1 GeV?
wfpie5to5000in2017vsdata_origvssign788d2_pfclu_ho_log10e

**Comment by kpedro88** [comment]
@abdoulline @mmusich GTs `81X_upgrade2017_realistic_v18` and `81X_upgrade2017_realistic_v19` have `HcalSiPMParameters_2017_v2.0_mc` which still has non-zero dark current for 2017 HO. Can we make a fixed record/tag?

**Comment by mmusich** [comment]
@kpedro88 I see that a new tag: `HcalSiPMParameters_2017_v3.0_mc` exists, but it has never been requested:

https://cms-conddb.cern.ch/cmsDbBrowser/requests_management/Prod/tag/HcalSiPMParameters_2017_v3.0_mc/HcalSiPMParametersRcd

is it meant to fix this issue? @abdoulline please confirm.

**Comment by abdoulline** [comment]
Please, don't use/consider  HcalSiPMParameters_2017_v3.0_mc (it was erroneous),
Let me see (shortly) where we have had an omission... I thought everything has been fixed in this HO domain...

**Comment by kpedro88** [comment]
@abdoulline I think I had previously just looked at Run1 and Run2, assuming that 2017 was correct...

**Comment by abdoulline** [comment]
@kpedro88 - probably yes, looking into some relevant emails earlier, I didn't see mentioning of HcalSiPMParameters for 2017. Let's try to quickly arrange for  new HcalSiPMParameters_2017_v4.0_mc ...

**Comment by slava77** [comment]
Run1 HO is sensible, as you describe.

The 2017 HO is nonsense.

**Comment by slava77** [comment]
On 10/27/16 9:23 AM, Kevin Pedro wrote:
> @abdoulline <https://github.com/abdoulline> @mmusich
> <https://github.com/mmusich> GTs |81X_upgrade2017_realistic_v18| and
> |81X_upgrade2017_realistic_v19| have |HcalSiPMParameters_2017_v2.0_mc|
> which still has non-zero dark current for 2017 HO. Can we make a fixed
> record/tag?

I suppose, this explains the excess of low-E hits in my plot.

**Comment by kpedro88** [comment]
@slava77 yes, that appears to be the cause.

**Comment by abdoulline** [comment]
HcalSiPMParameters_2017_v4.0_mc is about to be submitted by Walter...

**Comment by mmusich** [comment]
@kpedro88 please merge: 

https://github.com/kpedro88/cmssw/pull/3

it will supply the needed payloads for testing. Incidentally since autoCond is evolving fast you'll need to rebase after merge. 

@abdoulline I sincerely hope we are done now with HO :)

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
@mmusich  me too :)

**Comment by kpedro88** [comment]
@slava77 do things look satisfactory now?

**Comment by slava77** [comment]
@kpedro88 
I'll try to get to this by tomorrow

**Comment by mmusich** [comment]
@kpedro88: after that #16301 has been merged, you have now to rebase once again, but I'll need to provide updated Global Tags with the correct geometry content. I'll come to this later today.

**Comment by kpedro88** [comment]
@mmusich okay, I'll rebase when you send the tags

**Comment by mmusich** [comment]
@kpedro88, here they are:
https://github.com/kpedro88/cmssw/pull/4

**Comment by mmusich** [comment]
@kpedro88 whoops: it's `81X_upgrade2017_realistic_v21` not `81X_upgrade2017_realistic_v20`. Would you mind fixing it?

**Comment by kpedro88** [comment]
@mmusich will fix during rebase

**Comment by mmusich** [comment]
thanks - sorry

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@slava77 @civanch @mmusich @ggovi please sign ASAP

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@slava77 @mmusich @ggovi @davidlange6 this PR is important for pre16, and other PRs need to come on top of it

**Comment by kpedro88** [comment]
@slava77 @mmusich @ggovi @davidlange6 I am obliged to keep nagging about this PR for pre16

**Comment by davidlange6** [comment]
Look so like it's had a fairly active and productive review during usual (and recent) working days....

**Comment by kpedro88** [comment]
It did have a productive review and now needs signatures. #16365 is needed for phase2 and conflicts with this, so needs at least a day to be rebased/tested/signed after this is merged. We also expect another PR to add ZS thresholds (still being finalized). Each PR does not exist in a vacuum, and if the Nov 1 deadline for pre16 is going to be enforced, there remains a lot of work to do.

**Comment by slava77** [comment]
On 10/30/16 10:44 AM, Kevin Pedro wrote:
> @slava77 <https://github.com/slava77> @mmusich
> <https://github.com/mmusich> @ggovi <https://github.com/ggovi>
> @davidlange6 <https://github.com/davidlange6> I am obliged to keep
> nagging about this PR for pre16

As usual, any basic validation plots for the full dynamic range are
missing for the last update.
So, it takes some time to remake. (Also, it's the weekend.)
This is on top of two already failed iterations.
Please take this in consideration for the future HCAL PRs and your
expectations and ideas on how to speedup review.

I'm hoping to get to this in time for pre16.

**Comment by kpedro88** [comment]
Well, the change since the last round was only in the SiPMParameters tag to remove dark current in HO.

No HO plots show up in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-10-28-1100+16315/16651/validateJR/all_OldVSNew_TTbar13TeV2017wf10024p0/, which indicates the change was successful. (If we don't trust the code that identifies plots with differences to be shown in the comparison, that is a problem that should be addressed.) The HBHE plots there show minor differences compatible with the change in the sim-level saturation/recovery parameter and corresponding nonlinearity correction introduced in reco.

**Comment by slava77** [comment]
On 10/30/16 11:02 AM, Kevin Pedro wrote:
> Well, the change since the last round was only in the SiPMParameters tag
> to remove dark current in HO.
> 
> No HO plots show up in
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-10-28-1100+16315/16651/validateJR/all_OldVSNew_TTbar13TeV2017wf10024p0/,
> which indicates the change was successful. (If we don't trust the code
> that identifies plots with differences to be shown in the comparison,
> that is a problem that should be addressed.) The HBHE plots there show
> minor differences compatible with the change in the sim-level
> saturation/recovery parameter and corresponding nonlinearity correction
> introduced in reco.

Where can I see clearly that the last GT update
touched only HO?

**Comment by davidlange6** [comment]
Right but complaining that updates made Friday late are not reviewed on Sunday sounds like the wrong expectation (even if Slava is indeed working)

Cheers
David


On 30 Oct 2016, at 18:53, Kevin Pedro <notifications@github.com<mailto:notifications@github.com>> wrote:


It did have a productive review and now needs signatures. #16365<https://github.com/cms-sw/cmssw/pull/16365> is needed for phase2 and conflicts with this, so needs at least a day to be rebased/tested/signed after this is merged. We also expect another PR to add ZS thresholds (still being finalized). Each PR does not exist in a vacuum, and if the Nov 1 deadline for pre16 is going to be enforced, there remains a lot of work to do.

**Comment by kpedro88** [comment]
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v20/81X_upgrade2017_realistic_v21 shows that only HcalSiPMParameters was changed.

Using the config [dumpHcalCond_test_cfg.py](http://kjplanet.com/pr/dumpHcalCond_test_cfg.py), I dumped `HcalSiPMParameters_2017_v2.0_mc` and `HcalSiPMParameters_2017_v4.0_mc` and made a [diff](http://kjplanet.com/pr/diff_SiPMParameters_2017_v2.0_v4.0.txt), showing only the expected change in the HO dark current value.

I don't like working on weekends either, but I don't decide the deadlines, I just have to live with them.

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16315 b41c70b
- code and GT changes now appear to be in line with expectations
- jenkins tests pass and show changes in HO in run1 (as posted in https://github.com/cms-sw/cmssw/pull/16315#issuecomment-256519774) and in HE in 2017
- local tests with higher stats show small impact on jet response

based on dijet 15 to 3 TeV sample (wf 1338 equivalent) in 2017 setup
wf1338in2017v4_ak4calo_corogen_vs_pt_e
wf1338in2017v4_ak4pf_corogen_vs_pt_e

**Comment by kpedro88** [comment]
thanks!

@ggovi the DB change is just adding `HcalMCParams` to `HcalDbService`

File: CalibCalorimetry/HcalAlgos/src/HcalSiPMnonlinearity.cc [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+#include "Math/Polynomial.h"
+#include "CalibCalorimetry/HcalAlgos/interface/HcalSiPMnonlinearity.h"
+
+// Assume parameters come to us from the reco side; i.e.,
+// true pes = corfun(pixelsfired). But we want to invert that.
+//
+int HcalSiPMnonlinearity::getPixelsFired(int inpes) const
+{
+  ROOT::Math::Polynomial p(a2,b1,c0,-inpes);
+  std::vector<double> roots = p.FindRealRoots();
```
Comment (davidlange6) [inline CalibCalorimetry/HcalAlgos/src/HcalSiPMnonlinearity.cc]: calling gsl directly would likely be better in the long term (seems this function is not yet used)

Comment (kpedro88) [inline CalibCalorimetry/HcalAlgos/src/HcalSiPMnonlinearity.cc]: Yes, right now this is just left in place for future studies.

The ROOT functions do a fair amount of useful processing (it's not just a direct clone of gsl), so I would prefer to leave it this way.

File: SimCalorimetry/HcalSimAlgos/src/HcalSiPMShape.cc [hunk 3]
```diff
@@ -35,15 +36,28 @@ void HcalSiPMShape::computeShape() {
...
-double HcalSiPMShape::analyticPulseShape(double t) const {
-  // taken from fit to laser measurement taken by Iouri M. in Spring 2016.
-  double A1(5.204/6.94419), sigma1_shape(0.5387), theta1_loc(-0.3976), m1_scale(4.428);
-  double A2(1.855/6.94419), sigma2_shape(0.8132), theta2_loc(7.025),   m2_scale(12.29);
-  return
-    onePulse(t,A1,sigma1_shape,theta1_loc,m1_scale) +
-    onePulse(t,A2,sigma2_shape,theta2_loc,m2_scale);
+double HcalSiPMShape::analyticPulseShape(double t, unsigned int signalShape) const {
+  if(signalShape==HcalShapes::ZECOTEK || signalShape==HcalShapes::HAMAMATSU){
+    double A1(0.08757), c1(-0.5257), t01(2.4013), s1(0.6721);
```
Comment (davidlange6) [inline SimCalorimetry/HcalSimAlgos/src/HcalSiPMShape.cc]: please document the source of these magic numbers

**Comment by davidlange6** [comment]
@kpedro88 -three small comments that can be considered on one of the promised follow-on prs. thanks

File: SimCalorimetry/HcalSimAlgos/src/HcalSiPM.cc [hunk 4]
```diff
@@ -164,7 +174,15 @@ void HcalSiPM::setTemperatureDependence(double dTemp) {
 
 double HcalSiPM::cellCharge(double deltaTime) const {
   if (deltaTime <= 0.) return 0.;
-  if (deltaTime > 10./theTauInv) return 1.;
-  double result(1. - std::exp(-deltaTime*theTauInv));
+  if (deltaTime > 10.*theTau) return 1.;
```
Comment (kpedro88) [inline SimCalorimetry/HcalSimAlgos/src/HcalSiPM.cc]: I was just trying to avoid multiple inversions of the tau parameter. I will run igprof to check if there is a performance penalty.

**Comment by davidlange6** [comment]
> On Oct 31, 2016, at 4:24 PM, Kevin Pedro <notifications@github.com> wrote:
> 
> @kpedro88 commented on this pull request.
> 
> In CalibCalorimetry/HcalAlgos/src/HcalSiPMnonlinearity.cc:
> 
> > @@ -0,0 +1,19 @@
> +#include <iostream>
> +#include "Math/Polynomial.h"
> +#include "CalibCalorimetry/HcalAlgos/interface/HcalSiPMnonlinearity.h"
> +
> +// Assume parameters come to us from the reco side; i.e.,
> +// true pes = corfun(pixelsfired). But we want to invert that.
> +//
> +int HcalSiPMnonlinearity::getPixelsFired(int inpes) const
> +{
> +  ROOT::Math::Polynomial p(a2,b1,c0,-inpes);
> +  std::vector<double> roots = p.FindRealRoots();
> 
> Yes, right now this is just left in place for future studies.
> 
> The ROOT functions do a fair amount of useful processing (it's not just a direct clone of gsl), so I would prefer to leave it this way.

almost none of the ROOT overhead is actually taken advantage of in this usage. but yes, it saves you a handful of lines (at a substantial cost of operational overhead) - of course it may or may not matter depending on how this function gets used

**Comment by davidlange6** [comment]
right, you need my change to go back to one inversion…

File: SimCalorimetry/HcalSimAlgos/src/HcalSiPMShape.cc (hunk 3 above)
Comment (kpedro88) [inline SimCalorimetry/HcalSimAlgos/src/HcalSiPMShape.cc]: Well, these were never documented to begin with... I just restored the HO pulse shape from earlier versions: https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_0_pre8/SimCalorimetry/HcalSimAlgos/src/HcalSiPMShape.cc

I can add a note like "HO SiPM pulse shape fit from Jake Anderson ca. 2013".
