### PR TITLE
[RECO-UPGRADE] [GCC12] Disable cuda builds if cuda does not support gcc version

### PR DESCRIPTION
**Pull request by smuzaffar**
Disabled building cuda tests/binaries if cuda does not support gcc version e.g. currently cuda with gcc12 does not work.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
gcc12 IBs are broken and errors in https://github.com/cms-sw/cmssw/pull/38396#issuecomment-1158541789 are expected

**Comment by smuzaffar** [comment]
so looks like the cuda code is not optional. Looks like there are some `*GPU*.cc e.g EERecHitGPU.cc , EERecHitGPUtoSoA.cc` files which requires cuda code
```
EERecHitGPU.cc:(.text+0x208c): undefined reference to `KernelManagerHGCalRecHit::run_kernels(KernelConstantData<HGCeeUncalibRecHitConstantData> const*, CUstream_st* const&)'
EERecHitGPU.cc:(.text+0x20d9): undefined reference to `KernelManagerHGCalRecHit::~KernelManagerHGCalRecHit()'
```
Is the code in `*GPU*.cc` really required  for non gpu runs? If not then we can skip these files too

**Comment by clacaputo** [comment]
> Is the code in `*GPU*.cc` really required for non gpu runs? If not then we can skip these files too

Naively, I'd say no, they shouldn’t rely on GPU code for non-GPU runs, but maybe @cms-sw/heterogeneous-l2 can comment.

**Comment by fwyzard** [comment]
@clacaputo you are probably right.
The best approach would be to split the plugin in two: one working entirely on CPU, and one with the GU code.
However, I would suggest to let the authors of the package to take care of this.

**Comment by clacaputo** [comment]
Hi @smuzaffar `EERecHitGPU.cc , EERecHitGPUtoSoA.cc` seem to be used only in some `test` code, so they can be easily skipped. Concerning the other plugins showing the same behaviour (do you have a list?), maybe we could open an issue on ask the main developer to address the splitting suggested by @fwyzard .

**Comment by clacaputo** [comment]
@cmsbuild please test for el8_amd64_gcc12

**Comment by clacaputo** [comment]
Hi @smuzaffar , I've tried to refresh the test results using `el8_amd64_gcc12`, but the test failed with this error:

`'Unable to find CMSSW release for CMSSW_12_5_X/el8_amd64_gcc12'`

Am I doing something wrong?

**Comment by clacaputo** [comment]
@cmsbuild please test for el8_amd64_gcc12

**Comment by fwyzard** [comment]
by the way, do we have gcc12 IBs to test this locally ?

**Comment by smuzaffar** [comment]
@fwyzard as gcc12 IBs are broken so we only build those on demand. I just have started one which should be available for test later in the evening

**Comment by fwyzard** [comment]
Thanks - I won't be able to have a look until next week, but I guess the IB should stay around for another 10 days or so.

**Comment by fwyzard** [comment]
@smuzaffar 

> as gcc12 IBs are broken so we only build those on demand. I just have started one which should be available for test later in the evening

Ah... they are _very_ broken; we don't seem to get any CMSSW built at all :-/

It is pretty low on my priority, but, is there a way to see what is failing ?
Other than attempting the full build locally, of course.

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

**Comment by clacaputo** [comment]
@smuzaffar , do we still need this PR in?

**Comment by smuzaffar** [comment]
No, not really, closing it
