### PR TITLE
Fix trackingOnly DQM

### PR DESCRIPTION
**Pull request by makortel**
TrackingOnly DQM currently fails with

```
$ cmsDriver.py step3_trk --datatier DQMIO --conditions auto:run1_mc -s RAW2DIGI,RECO:reconstruction_trackingOnly,VALIDATION:@trackingOnlyValidation,DQM:@trackingOnlyDQM --eventcontent DQM -n 100 --filein file:step2.root --fileout file:step3_inDQM.root --no_exec
...
Traceback (most recent call last):
  File ".../CMSSW_8_0_0/bin/slc6_amd64_gcc493/cmsDriver.py", line 55, in <module>
    run()
  File ".../CMSSW_8_0_0/bin/slc6_amd64_gcc493/cmsDriver.py", line 27, in run
    configBuilder.prepare()
  File ".../CMSSW_8_0_0/python/Configuration/Applications/ConfigBuilder.py", line 2058, in prepare
    self.addStandardSequences()
  File ".../CMSSW_8_0_0/python/Configuration/Applications/ConfigBuilder.py", line 741, in addStandardSequences
    getattr(self,"prepare_"+stepName)(sequence = '+'.join(stepSpec))
  File ".../CMSSW_8_0_0/python/Configuration/Applications/ConfigBuilder.py", line 1961, in prepare_DQM
    setattr(self.process,pathName, cms.Path( getattr(self.process, sequence) ) )
AttributeError: 'Process' object has no attribute 'DQMHarvestTracking'
```

I believe it got broken in #12604, and this PR fixes it.

Tested in 8_0_0, no changes expected. The branch is based on 8_0_0, so placing a corresponding PR for 80X, if needed, is trivial.

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by deguio** [comment]
+1
thanks. I simply missed that entry in my original PR.
sorry about that.
F.

**Comment by davidlange6** [comment]
+1
