### PR TITLE
Update TensorFlow interface for 1.5.0.

### PR DESCRIPTION
**Pull request by riga**
This PR is the continuation of PR #22147 and contains changes to PhysicsTools/TensorFlow to work with TensorFlow 1.5.0.

The migration to version 1.5.0 in cmsdist is documented in cms-sw/cmsdist#3717.

### CODE REVIEW

**Comment by riga** [comment]
The code check complains about a missing header,

```
/.../CMSSW_10_1_X_2018-02-17-1100/src/PhysicsTools/TensorFlow/src/NTSession.h:49:10: error:
'tensorflow/core/common_runtime/graph_execution_state.h' file not found
```

which is added by cms-sw/cmsdist#3717. @slava77 @smuzaffar Is there anything I can do to make this PR consider cms-sw/cmsdist#3717 for code checks and tests?

**Comment by smuzaffar** [comment]
please test with  cms-sw/cmsdist#3717

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3747

**Comment by riga** [comment]
I forgot to rename the `session_runs` variable. Should be fixed now.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3747

File: PhysicsTools/TensorFlow/src/NTSession.cc [hunk 1]
```diff
@@ -12,13 +12,10 @@ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 ==============================================================================*/
-//NOTE: The memory layout of the Node class changes depending on if NDEBUG was
-// set when tensorflow was compiled. The reason is Node class holds two edgeset
-// class instances and edgeset adds a member data if NDEBUG is set
```
Comment (slava77) [inline PhysicsTools/TensorFlow/src/NTSession.cc]: the NDEBUG define is not in the upstream.
Should this comment be still kept (perhaps to be moved to the part following "this file is an adaptation"?

File: PhysicsTools/TensorFlow/src/NTSession.cc [hunk 2]
```diff
@@ -177,32 +171,9 @@ static NTSessionRegistrar registrar;
...
-// Based on these assumptions, we can use the same thread pool for
-// both "non-blocking" and "blocking" OpKernels on Android.
-//
-// This may change down the road when we add support for multiple
-// devices that run concurrently, in which case we will need to
-// revisit this decision.
+// Override to allow CMSSW FWK to schedule
 void NTSession::SchedClosure(std::function<void()> c) {
-
-  // On Android, there is no implementation of ThreadPool that takes
```
Comment (slava77) [inline PhysicsTools/TensorFlow/src/NTSession.cc]: the notes about Android are in the upstream version.
Should they be put back?

File: PhysicsTools/TensorFlow/src/NTSession.cc [hunk 3]
```diff
@@ -474,27 +444,32 @@ Status NTSession::Run(const RunOptions& run_options,
           ((measure_step_count + 1) % build_cost_model_every == 0);
```
Comment (slava77) [inline PhysicsTools/TensorFlow/src/NTSession.cc]: the upstream has the following around L452:

```diff

   args.rendezvous = run_state.rendez;
   args.cancellation_manager = &step_cancellation_manager;
-  args.runner = [this, pool](Executor::Args::Closure c) {
-    SchedClosure(pool, std::move(c));
-  };
+
   args.session_state = &session_state_;
   args.tensor_store = &run_state.tensor_store;
   args.step_container = &run_state.step_container;

```

should it be kept here?

File: PhysicsTools/TensorFlow/src/NTSession.cc [hunk 4]
```diff
@@ -523,13 +498,10 @@ Status NTSession::Run(const RunOptions& run_options,
     run_state.status.Update(errors::Cancelled("Run call was cancelled"));
```
Comment (slava77) [inline PhysicsTools/TensorFlow/src/NTSession.cc]: around L510 the upstream has the following change

```diff
     return errors::Cancelled("Run call was cancelled");
   }

+  Executor::Args::Runner default_runner = [this,
+                                           pool](Executor::Args::Closure c) {
+    SchedClosure(pool, std::move(c));
+  };
   for (const auto& item : executors_and_keys->items) {
+    // TODO(zhengxq): support partial run.
+    // TODO(zhengxq): if the device picks its own threadpool, we need to assign
+    //     less threads to the main compute pool by default.
+    thread::ThreadPool* device_thread_pool =
+        item.device->tensorflow_device_thread_pool();
+    if (!device_thread_pool) {
+      args.runner = default_runner;
+    } else {
+      args.runner = [this, device_thread_pool](Executor::Args::Closure c) {
+        SchedClosure(device_thread_pool, std::move(c));
+      };
+    }
     item.executor->RunAsync(args, barrier->Get());
   }

```

should it be made here?

**Comment by smuzaffar** [comment]
@riga, can you please take care of the comments made by @slava77  above. 
We should try to get in to get aarch64 IBs working again.

File: PhysicsTools/TensorFlow/src/NTSession.cc (hunk 1 above)
Comment (riga) [reply PhysicsTools/TensorFlow/src/NTSession.cc]: Yes, since we use it, we should keep the note here.

File: PhysicsTools/TensorFlow/src/NTSession.cc (hunk 2 above)
Comment (riga) [reply PhysicsTools/TensorFlow/src/NTSession.cc]: I'll add them back. Might be helpful when comparing revisions in future TF updates.

File: PhysicsTools/TensorFlow/src/NTSession.cc (hunk 3 above)
Comment (riga) [reply PhysicsTools/TensorFlow/src/NTSession.cc]: Yes, I added those lines again since the changes you marked in your next comment need to be reverted in order to prevent TF from managing its own thread pool again.

File: PhysicsTools/TensorFlow/src/NTSession.cc (hunk 4 above)
Comment (riga) [reply PhysicsTools/TensorFlow/src/NTSession.cc]: See previous comment. The if-clause in the loop body should always be true, which is why I moved the `args.runner = default_runner;` line outside the loop and also removed the `default_runner` variable.

Comment (slava77) [reply PhysicsTools/TensorFlow/src/NTSession.cc]: we should remove any optimizations with respect to the upstream code except for the functional changes that we need. This will be very useful when the upstream is refactored or updated in the future.

If the improvement is valid for the upstream, perhaps it's better to submit a PR there.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3747

**Comment by riga** [comment]
I tracked down the two differences in the reco comparison results (
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-22-1100+22260/25206/validateJR/all_OldVSNew_TTbar13TeVPU2017wf10224p0), but fail to see the relation to the last commit in this PR (d13b2a5). There were no differences before.

@slava77 @smuzaffar Do you have any advice?

**Comment by perrotta** [comment]
@riga : that difference only points out that there is a different number of warning messages in the log. In these PU workflows those "warnings" usually refer to the notifications of opening of the MinBias files used for the PU.

If you compare 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22260/26247/runTheMatrix-results/10224.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU.log
with
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_10_1_X_2018-02-22-1100/slc6_amd64_gcc630/-GenuineIntel/matrix-results/10224.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU.log
you can see that there is one more opening of the PU root files.

In any case, nothing that can affect this PR or that you have to worry about :-)

**Comment by riga** [comment]
Ah, that clears things up. I wasn't sure what `Reco.obj@.size()` was referring to.
Thanks!

File: PhysicsTools/TensorFlow/src/NTSession.cc (hunk 4 above)
Comment (slava77) [reply PhysicsTools/TensorFlow/src/NTSession.cc]: IIUC, there is still some optimization present here from our side, which leads to the change in the loop body.
Please either restore possibly redundant change or add a clear comment about the modification made from CMSSW side.

File: PhysicsTools/TensorFlow/src/NTSession.cc [hunk 5]
```diff
@@ -507,6 +498,9 @@ Status NTSession::Run(const RunOptions& run_options,
     return errors::Cancelled("Run call was cancelled");
   }
 
+  args.runner = [this](Executor::Args::Closure c) {
+    SchedClosure(std::move(c));
+  };
   for (const auto& item : executors_and_keys->items) {
     item.executor->RunAsync(args, barrier->Get());
```
Comment (slava77) [inline PhysicsTools/TensorFlow/src/NTSession.cc]: this is the loop discussed in https://github.com/cms-sw/cmssw/pull/22260/files#r169140455

**Comment by slava77** [comment]
@riga 
please clarify the plans with the remaining differences with the upstream.
I just wanted to check that the comment didn't just go unnoticed.

File: PhysicsTools/TensorFlow/src/NTSession.cc (hunk 4 above)
Comment (riga) [reply PhysicsTools/TensorFlow/src/NTSession.cc]: Ok, makes sense. I will update that part.

File: PhysicsTools/TensorFlow/src/NTSession.cc (hunk 5 above)
Comment (riga) [reply PhysicsTools/TensorFlow/src/NTSession.cc]: ✔︎

**Comment by riga** [comment]
I just pushed the required changes to reduce the number of changes w.r.t. to the upstream

**Comment by slava77** [comment]
> -code-checks
this is fun. It looks like the tensorflow upstream code does not conform to our code-checks anymore. The same code diff has passed checks previously.
@fabiocos @smuzaffar did the rules change recently?

@davidlange6 @smuzaffar 
how do we tell code-checks to ignore a change?

**Comment by davidlange6** [comment]
this proposed change from clang-tidy looks useful and even correct depending on the API of GraphExecutionState. Perhaps its related to the changes from SimpeGraphExecutionState to GraphExecutionState made in this PR rather than some upstream code that you think is unchanged?

anyway, https://stackoverflow.com/questions/37950439/inline-way-to-disable-clang-tidy-checks

**Comment by smuzaffar** [comment]
@slava77 , till now I was manually setting check checks to pass state as in this case code checker is using old tensorflow (1.3) external with cmssw code which should be checked with tensorflow 1.5.
I can set again set it to passed so that tests can run

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3747

**Comment by slava77** [comment]
On 3/2/18 6:17 AM, Malik Shahzad Muzaffar wrote:
> @slava77 <https://github.com/slava77> , till now I was manually setting
> check checks to pass state as in this case code checker is using old
> tensorflow (1.3) external with cmssw code which should be checked with
> tensorflow 1.5.
> I can set again set it to passed so that tests can run
> 

Thank you.

@Dr15Jones
is this a good enough reason to move this code to the cms-externals?
We treat it differently, even though it's a part of CMSSW.

**Comment by Dr15Jones** [comment]
@slava77 isn't this the same problem we'd have with any calls to 3rd party code? E.g. if Pythia8 or ROOT changed an API we'd have the same problem.

**Comment by slava77** [comment]
On 3/2/18 7:06 AM, Chris Jones wrote:
> @slava77 <https://github.com/slava77> isn't this the same problem we'd
> have with any calls to 3rd party code? E.g. if Pythia8 or ROOT changed
> an API we'd have the same problem.
> 


but we do not reimplement parts of pythia8 or ROOT.
Or do we?
Please give me an example, in case we did something similar.
For these cases, are we doing the same with code-checks?

**Comment by Dr15Jones** [comment]
@slava77 Personally, anytime we inherit from a 3rd party class we are essentially 're-implementing' something. So TFileAdaptor and the whole clang static analyzer seem to fit that bill.

**Comment by slava77** [comment]
what did we do with the code-checks in these cases?
Do we make the CMSSW reimplementation conformant to our style?

**Comment by Dr15Jones** [comment]
I think either we made the changes to conform, or they happen to already conform.

**Comment by Dr15Jones** [comment]
@slava77 If you really want, we could move this code to its own repository, completely separate from CMSSW or tensorflow. However, then building and testing that code outside of the production system makes it much harder to do (can't use scram, have to have new build files, e.g. CMake or Makefile, can't use our unit testing infrastructor, etc).

**Comment by slava77** [comment]
> @slava77 If you really want, we could move this code to its own repository

I'm trying to understand what's more manageable.

For now it sounds like we should just treat code-checks here in a regular way and apply them to this PR instead of manually skipping them.

**Comment by slava77** [comment]
> ---> test testhep_ml had ERRORS
---> test testImports had ERRORS

I see some indications that both of these tests are failing in the IB as well.
@smuzaffar please confirm.
Thanks.

**Comment by davidlange6** [comment]
those are not related to this PR - not quite sure of the cmsdist commit this was tested against, but certainly related to recent changes there

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22260	9334559 
- alignment of CMSSW implementation of TF session variants to match the new release of tensorflow.
- jenkins tests pass and comparisons show no differences.

**Comment by fabiocos** [comment]
@slava77 @smuzaffar I understand that the integration of this PR requires the integration of cms-sw/cmsdist#3747 as a pre-requisite

**Comment by slava77** [comment]
On 3/4/18 9:26 AM, Fabio Cossutti wrote:
> @slava77 <https://github.com/slava77> @smuzaffar
> <https://github.com/smuzaffar> I understand that the integration of this
> PR requires the integration of cms-sw/cmsdist#3747
> <https://github.com/cms-sw/cmsdist/pull/3747> as a pre-requisite
> 

it should be done simultaneously

**Comment by smuzaffar** [comment]
@fabiocos , as slava wrote, both of these should be merged for same IB. As jenkins is under heavy load today, so I would suggest that we merge these for tonight's 23h00 IB (just before the IB start).

**Comment by fabiocos** [comment]
@smuzaffar yes, I agree, let's keep it on hold for the time being

**Comment by fabiocos** [comment]
cms-sw/cmsdist#3747 has been merged

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge
