### PR TITLE
[UBSAN] added deps on TrackerRecHit2D for BaseTrackerRecHit

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes UBSAN link error [a] which was introduced after https://github.com/cms-sw/cmssw/pull/47441 intergation

[a] https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_15_1_UBSAN_X_2025-03-07-2300/SimDataFormats/TrackingAnalysis
```
 ld.bfd: tmp/el8_amd64_gcc12/src/SimDataFormats/TrackingAnalysis/src/SimDataFormatsTrackingAnalysis/SimDoublets.cc.o:(.data.rel+0x758): undefined reference to `typeinfo for BaseTrackerRecHit'
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for CMSSW_15_1_UBSAN_X

**Comment by smuzaffar** [comment]
Please test

**Comment by smuzaffar** [comment]
@cms-sw/simulation-l2 , can you please review this? This fixes the UBSAN build/link errors

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1
