### ISSUE TITLE
Build CMSSW_12_1_0_pre3

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#35279]

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
@smuzaffar @makortel   There is a build error for slc7_amd64_gcc10,  as reported by @perrotta in 
https://github.com/cms-sw/cmssw/pull/35240#issuecomment-919704154
Do you have any idea on this? Or if there is plan for gcc10 validation,  can we go ahead with this build of 12_1_0_pre3?  Thanks!
Adding also @bsunanda 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/auto-build-release/CMSSW_12_1_0_pre3-slc7_amd64_gcc10/3176/LOGS/cms/cmssw/CMSSW_12_1_0_pre3/log
/data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_1_0_pre3-slc7_amd64_gcc10/build/CMSSW_12_1_0_pre3-build/slc7_amd64_gcc10/external/gcc/10.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: tmp/slc7_amd64_gcc10/src/Calibration/HcalCalibAlgos/plugins/CalibrationHcalCalibAlgosPlugins/HOCalibAnalyzer.cc.o: in function `HOCalibAnalyzer::HOCalibAnalyzer(edm::ParameterSet const&)':
HOCalibAnalyzer.cc:(.text+0x598d): undefined reference to `HOCalibAnalyzer::nphimx'
/data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_1_0_pre3-slc7_amd64_gcc10/build/CMSSW_12_1_0_pre3-build/slc7_amd64_gcc10/external/gcc/10.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: tmp/slc7_amd64_gcc10/src/Calibration/HcalCalibAlgos/plugins/CalibrationHcalCalibAlgosPlugins/HOCalibAnalyzer.cc.o: in function `HOCalibAnalyzer::HOCalibAnalyzer(edm::ParameterSet const&)':
HOCalibAnalyzer.cc:(.text+0x739d): undefined reference to `HOCalibAnalyzer::nphimx'
collect2: error: ld returned 1 exit status
gmake: *** [tmp/slc7_amd64_gcc10/src/Calibration/HcalCalibAlgos/plugins/CalibrationHcalCalibAlgosPlugins/libCalibrationHcalCalibAlgosPlugins.so] Error 1
Entering library rule at Calibration/HcalCalibAlgos

**Comment by makortel** [comment]
> Or if there is NO plan for gcc10 validation, can we go ahead with this build of 12_1_0_pre3?

I'd think that since there has been no specific fix for the reported discrepancy in GEM plots (that seem more like red herring caused by non-gaussian fluctuations), strictly speaking we would not need a new validation campaign for gcc10. A counter-argument would be that lot's of other developments have been merged in between that have not been validated for gcc10. Counter-counter-argument would be that gcc10 will be implicitly re-validated when we switch to it for production.

**Comment by qliphy** [comment]
abort

**Comment by qliphy** [comment]
> > Or if there is NO plan for gcc10 validation, can we go ahead with this build of 12_1_0_pre3?
> 
> I'd think that since there has been no specific fix for the reported discrepancy in GEM plots (that seem more like red herring caused by non-gaussian fluctuations), strictly speaking we would not need a new validation campaign for gcc10. A counter-argument would be that lot's of other developments have been merged in between that have not been validated for gcc10. Counter-counter-argument would be that gcc10 will be implicitly re-validated when we switch to it for production.

Thanks @makortel 
Now a fix has been merged   https://github.com/cms-sw/cmssw/pull/35282
Let's rebuild pre3.

**Comment by makortel** [comment]
> Now a fix has been merged #35282
> Let's rebuild pre3.

That works of course too :)
