### PR TITLE
typo: use correct variable name c27_

### PR DESCRIPTION
**Pull request by smuzaffar**
use the correct data member name `c27_`. This fixes the build error for DEBUG and clang analyzer

```
>> Analyzing  src/Geometry/HGCalCommonData/src/HGCalCellOffset.cc 
  [src/Geometry/HGCalCommonData/src/HGCGuardRing.cc:26](https://github.com/cms-sw/cmssw/blob/CMSSW_15_1_X_2025-06-01-2300/Geometry/HGCalCommonData/src/HGCGuardRing.cc#L26):48: error: use of undeclared identifier 'c77_'; did you mean 'c27_'?
    26 |                              << c22_ << ":" << c77_;
      |                                                ^~~~
      |                                                c27_
src/Geometry/HGCalCommonData/interface/HGCGuardRing.h:27:55: note: 'c27_' declared here
   27 |   double offset_, offsetPartial_, xmax_, ymax_, c22_, c27_;
      |                                                       ^
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , this PR fixes a typo introduced in https://github.com/cms-sw/cmssw/pull/48208/files#diff-3d20be58d1567b3b9a57ebfec5c80ff30271155704b15b35469453df3d6021deR25 (clearly visible in PR tests https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5a2607/46446/summary.html ). Feel free to integrate it without waiting for signatures.

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge
