### PR TITLE
Complete EventSetup-consumes migration for {Ecal,Hcal}HaloDataProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is part of #31061, and part of addressing failures in #31746.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
> **Failed tests: HeaderConsistency**

```
RecoMET/METAlgorithms/interface/HcalHaloAlgo.h:42:47: error: expected ')' before 'iC'
   explicit HcalHaloAlgo(edm::ConsumesCollector iC);
```
looks like an include is missing

**Comment by makortel** [comment]
> looks like an include is missing

Indeed...

**Comment by perrotta** [comment]
@makortel since you are there, you could also remove the duplicate include's in the implementation files

**Comment by makortel** [comment]
> you could also remove the duplicate include's in the implementation files

I decided to go with forward-declaration in `HcalHaloAlgo.h` instead, because `EcalHaloHalo.h` did that already.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction

- technical, migrates the geometry access in `EcalHaloDataProducer`, `HcalHaloDataProducer`, to `ESGetToken`
- the changes are otherwise minimal, e.g. no renaming of the existing (or modified) class members according to code rules
- tests pass with no reco difference as expected

**Comment by silviodonato** [comment]
+1
