### PR TITLE
[DBG] fix compilation error for dbg IBs

### PR DESCRIPTION
**Pull request by smuzaffar**
Fix the DBG compilation error. `ComponentShapeCollection` does not have `test()` member function. This was introduced in https://github.com/cms-sw/cmssw/pull/40855

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
@jhakala FYI

**Comment by civanch** [comment]
I would agree with this removal, moreover, in the class too many ifdef statements for debug printout. This is normal for time of development but for long term maintenance of the code this may be optimized. Also LogInfo may be substituted by LogVerbatim.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by jhakala** [comment]
I can confirm that this should be removed -- during development I had a `test` method but removed it, and forgot to get rid of this... apologies! And thanks for catching it @smuzaffar !
