### PR TITLE
[10.3.X] Introduce a special AlCaReco for Strip Small Bias Scans 

### PR DESCRIPTION
**Pull request by mmusich**
Greetings,
in the Tracker DPG we are trying to find a systematic solution to the chronic lack of RECO data-tier to analyze the output of SiStrip (small) Bias scans.
These scans are not affecting physics  (so they are standard production runs) and therefore normally only standard `AOD` output is available for the high rate (ie. non commissioning) datasets, which is not enough for the sensor aging monitoring purposes.
A viable solution would be to run one of our `ALCARECO` producers saving tracks and Strip clusters , but this solution might be in general disfavored  due to concerns about output dataset size.
Since we are scanning only few (fixed) power groups in a small bias scan and we are interested only in the clusters of tracks that have at least one hit on one of the modules being scanned, and we could select the output tracks to drastically reduce the data throughput. 
This is what has been implemented in the PR. 
A new track selector `CalibrationTrackSelectorFromDetIdList`, allowing to save a collection of track candidates leaving hits through a certain list of Tracker modules is employed in the novel `SiStripCalSmallBiasScan` `ALCARECO` producer.
The new `ALCARECO` producer has been added to several 2018 matrix workflows, including wf 136.85 which is in the short list used in PR tests. 
To allow the `ALCARECO` producer to run I have changed the `AlCaRecoTriggerBits` in the `run2_data_relval` and `run2_data_promptlike`  autoCond keys with temporary candidate GTs. 
@lpernie @arunhep @tocheng you might want to change them into full-fledged Global Tags.
I report here for completeness the average compressed size in bytes/event of the branches of the new `ALCARECO` compared with `SiStripCalMinBias`.

| Branch name | `SiStripCalMinBias` | `SiStripCalSmallBiasScan` |
| ------------- | ------------- |------------- |  
|recoTrackExtras                  |39791      |1982.09  |     
|TrackingRecHitsOwned             |27896.9    |1505.75  |     
|recoTracks                       |24399.7    |1160.07  |     
|SiStripClusteredmNewDetSetVector |22430.6    |1043.46  |     
|SiPixelClusteredmNewDetSetVector |13553.5    |1001.83  |     
|LumiScalerss_scalersRawToDigi    |1179.33    |951.02	|       
|EventProductProvenance           |1004.8     |786.41	|   
|DcsStatuss                       |349.09     |310.52	|   
|L1AcceptBunchCrossings           |217.85     |196.37	|   
|edmTriggerResults                |192.13     |181.04	|   
|DetIdedmEDCollection             |158.74     |144.52	|   
|edmTriggerResults                |127.18     |118.99	|   
|edmTriggerResults                |71.18      |63.34	|   
|L1GlobalTriggerReadoutRecord     |63.36      |56.98	|   
|EventAuxiliary                   |56.24      |52.17	|   
|EventSelections                  |28.55      |24.4	|   
|BranchListIndexes                |17.88      |15.5     |

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by prebello** [comment]
+1

**Comment by mmusich** [comment]
@tocheng @lpernie 
In the last commit I resolved the conflict caused by the merging of https://github.com/cms-sw/cmssw/pull/24381.
For completeness I report here the Global Tag changes:
# Summary of changes in Global Tags 
 
## RunII data 
 
   * **RunII Offline relval processing** : [103X_dataRun2_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_relval_v5) as [103X_dataRun2_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_relval_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_relval_v5/103X_dataRun2_relval_v4): 
      * Updated `AlCaRecoTriggerBits` to add `SiStripCalSmallBiasScan`

   * **RunII Prompt processing** : [103X_dataRun2_PromptLike_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_PromptLike_v5) as [103X_dataRun2_PromptLike_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_PromptLike_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_PromptLike_v5/103X_dataRun2_PromptLike_v3): 
      * Updated `AlCaRecoTriggerBits` to add `SiStripCalSmallBiasScan`

**Comment by lpernie** [comment]
please test

**Comment by mmusich** [comment]
based on the compilation errors that have nothing to do with my changes I would think the IB is broken.
@mrodozov can you confirm? Do we expect this to be fixed for the 11.00 IB?

**Comment by mrodozov** [comment]
it is so let me un-break it https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_10_3_X

**Comment by mrodozov** [comment]
https://github.com/cms-sw/cmssw/pull/24405#issuecomment-416894333 is fixing the IB issue but first has to go in

**Comment by mmusich** [comment]
as an IB with the fix is available can test be restarted?

**Comment by smuzaffar** [comment]
please test
yes, new ib with fix is now available.

**Comment by tocheng** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by mmusich** [comment]
Hi @prebello, you were OK with the changes here. Can you sign again (we changed only GT in the meanwhile)

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the update of the StandardSequences looks correct and coherent with the purpose of this PR

**Comment by fabiocos** [comment]
+1
