### PR TITLE
Support for TensorFlow 2.1

### PR DESCRIPTION
**Pull request by riga**
This PR provides changes to the PhysicsTools/TensorFlow interface to support TensorFlow 2.1.

It should be tested with ~https://github.com/cms-sw/cmsdist/pull/5427~  https://github.com/cms-sw/cmsdist/pull/5525.

As documented in https://github.com/cms-sw/cmsdist/pull/5427#issuecomment-567589830 , one of the tests (AOT compilation) currently fails. It requires a change to the`--entry_point` argument in the [cmssw-config/SCRAM/GMake/Makefile.dnn](https://github.com/cms-sw/cmssw-config/blob/4d6cd0fef1e12ae9f3e4a4cd5fda0917a940e085/SCRAM/GMake/Makefile.dnn#L42) build rule, which - as far as I can see - is no longer allowed to start with two underscores as of 2.0 (@smuzaffar). The [WIP] label can be removed once this is settled. All other tests pass.

The changes solely focus on 2.0 compatibility and thus target CPU support only. GPU support is planned and will be subject to a future PR, which will also contain features to simplify device placement and working with GPU memory (in coordination with the Patatrack team).

Smaller changes:
- Added `PhysicsTools/TensorFlow/python/tools.py` to aid graph reading and writing.
- Updated `DQMServices/Core/src/ROOTFilePB.pb.{cc,h}` for the new protobuf version (via ``protoc --cpp_out=`pwd` ROOTFilePB.proto``).

Edit: Performance comparison of the DeepJet model (from https://github.com/cms-sw/cmssw/pull/28711#issuecomment-581931722 below, using [testDeepJetPerformance.cc](https://gist.github.com/riga/5cb64ff74bc1c051b0be77c29df9daab)):

TF vs. ONNX

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters
 - pull_request = cms-sw/cmsdist#5427

**Comment by smuzaffar** [comment]
please test
thanks @riga

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by riga** [comment]
I fixed the [clang warnings](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-be28f3/4154/clang-new-warnings.log) that complained about unused `this` captures in lambdas.

Just out of curiosity: is there any particular reason why these warnings don't show up when compiling locally?

**Comment by smuzaffar** [comment]
@riga , these warnings are coming from clang . Locally when we build then we use only GCC.
By the way, I am testing it locally and get this error at runtime 

Workflow 25.0, step3

```
2020-01-07 17:34:06.592715: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
07-Jan-2020 17:34:06 CET  Closed file file:step2.root
----- Begin Fatal Exception 07-Jan-2020 17:34:06 CET-----------------------
An exception of category 'InvalidRun' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=DeepTauId label='deepTau2017v2p1'
Exception Message:
error while running session: Invalid argument: Session was not created with a graph before Run()!
----- End Fatal Exception -------------------------------------------------

```

**Comment by riga** [comment]
@smuzaffar This makes sense of course ...

I will look into that exception.

**Review by perrotta — COMMENTED** [review]
While comparing these ones with the corresponding changes in the TensorFlow 2.0 ```direct_session``` I notice that we miss here the ```bool DirectSession::ShouldUseRunHandlerPool``` method, and the option of running in caller's thread steered by ```bool run_in_caller_thread_```. I imagine that none of them is actually used here. Since I don't know in practice how do you propagate the updates from the central TensorFlow sessions, I wonder whether not being fully synchronized can potentially mess up a possible future update to a newer version. Can you reassure me?

**Comment by slava77** [comment]
@Dr15Jones 
you mentioned to me in the past that some other pattern of use of TF is possible.
I can't recall the details now. 
Did it imply that we may not need to use the CMS-specific session implementations?
If that could work, we may simplify our life with the ports.
Please remind/clarify.
Thank you.

**Comment by Dr15Jones** [comment]
>Did it imply that we may not need to use the CMS-specific session implementations?

@slava77 TF 2.0 is supposed to have better customization points which should allow us to have CMS specific behavior that can be implemented without doing large _cut-and-paste_ from TF.

**Comment by perrotta** [comment]
> > Did it imply that we may not need to use the CMS-specific session implementations?
> 
> @slava77 TF 2.0 is supposed to have better customization points which should allow us to have CMS specific behavior that can be implemented without doing large _cut-and-paste_ from TF.

Thank you @Dr15Jones !

@riga could you please verify if it is the case, and if so rewrite these interfaces to CMSSW in a more modular way with less cut-and-paste? It is certainly a larger effort now, but it will greatly reduce the amount of work to be done in case of further updates of the code

**Comment by riga** [comment]
@perrotta To adapt the changes made by TF in the `direct_session`, I also compare the diffs and manually check what needs to be done for our custom code. For the `NTSession` I usually remove all thread pool related code, and for the `TBBSession` I inject the use of the `taskArena` and `taskGroup` (as you have already seen in this PR's diffs). As you mentioned, this can be a cumbersome process and I would definitely welcome a more modular and portable solution, despite the larger short-term effort.

For the `NTSession`, as far as I see, setting `run_in_caller_thread_` to [true could already do the trick](https://github.com/tensorflow/tensorflow/blob/19673dfff5231471524cdcf257c0f5f5790696c4/tensorflow/core/common_runtime/direct_session.cc#L567).

The `TBBSession` requires a few more changes. @Dr15Jones By "better customization points", do you mean the introduced `RunHandlerPool`? I found similar requests for better thread pool modularization in TF, such as [this one](https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/KBr8xMy5QL0). I will investigate and report back.

**Comment by Dr15Jones** [comment]
@riga I actually initiated and contributed to the RFC to which you refer.

**Comment by riga** [comment]
@perrotta @Dr15Jones I came up with a first draft for the two thread pool implementations. You can find them [here](https://gist.github.com/riga/9542c6b0f2e97d9763eb59b4fb93e718).

`NoThreadPoolImpl` is trivial and runs without any unexpected surprise. I did a quick performance comparison w.r.t. TF 1.6 using the DeepJet model which looks quite promising:

image

For the `TBBThreadPoolImpl`, I copied the logic from the old `TBBSession` over to the `Schedule()` method. There are two open issues:
1. The interface should return the size of the thread pool in `NumThreads()`. Is there any way to access the number of threads that was set in cmsRun? My plan was to set `numThreads_` to that value in case `-1` is passed in the constructor, which is the default.
2. `GetCurrentThreadId()` is [supposed to return a logical thread index between 0 and `NumThreads() - 1`](https://gitlab.com/libeigen/eigen/blob/febd09dcc02c1429cd4abd3ddb3ed5108fcd8339/unsupported/Eigen/CXX11/src/ThreadPool/ThreadPoolInterface.h#L39). Do you have any suggestion how to achieve that with TBB?

**Comment by Dr15Jones** [comment]
@riga 

> The interface should return the size of the thread pool in NumThreads(). Is there any way to access the number of threads that was set in cmsRun? My plan was to set numThreads_ to that value in case -1 is passed in the constructor, which is the default.

TBB itself does not provide a way to ask it how many threads it was told to use. As for what number of threads are used if -1 is used in the configuration, we use the value returned by `tbb::task_scheduler_init::default_num_threads()`. 

As for finding out the number of threads used by the framework, the base classes for the modules are actually passed that information, however only ::global and ::limited have user virtual functions which can access that info at the moment: `void preallocate(PreallocationConfiguration const&)`

> GetCurrentThreadId() is supposed to return a logical thread index between 0 and NumThreads() - 1. Do you have any suggestion how to achieve that with TBB?

It could be done like
```
int GetCurrentThreadId() {
   std::static std::atomic<int> s_index{0};
   thread_local const int id = s_index++;
   return id;
}
```

**Comment by makortel** [comment]
> > GetCurrentThreadId() is supposed to return a logical thread index between 0 and NumThreads() - 1. Do you have any suggestion how to achieve that with TBB?
> 
> It could be done like
> 
> ```
> int GetCurrentThreadId() {
>    std::static std::atomic<int> s_index{0};
>    thread_local const int id = s_index++;
>    return id;
> }
> ```

@Dr15Jones How much does TBB guarantee that the threads stay in the pool? (my vague recollection is that it is best to assume TBB can do anything with the threads) I'm just wondering the likeliness of `s_index_` growing beyond `NumThreads()-1`, and what that would imply in TensorFlow/Eigen.

**Comment by riga** [comment]
Also, would it make sense to create a `TBBThreadPoolImpl` singleton at some central place where the configured number of threads is accessible? 

As indicated in [this example](https://github.com/tensorflow/tensorflow/blob/75018c797c82839c0910157f2b08417ac05c64fc/tensorflow/cc/client/client_session_test.cc#L216-L226), I think the `ThreadPoolOptions` that contain the desired thread pool instances should anyway be cached or stored somewhere, so there would only be one instance for `NoThreadPoolImpl` and one for `TBBThreadPoolImpl`.

**Comment by riga** [comment]
Status update: The custom thread pools are implemented and work. I am currently performing some last tests with ahead-of-time compilation of graphs and will push the changes in the beginning of next week. This should also resolve the build errors above.

**Comment by mrodozov** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmsdist/pull/5509

**Comment by riga** [comment]
I removed the session implementations, and added the custom thread pools including unit tests. Also, I ran some performance tests ([testDeepJetPerformance.cc](https://gist.github.com/riga/5cb64ff74bc1c051b0be77c29df9daab)), based on the deepjet model, to see how the inference time improves from the update to TF 2.1 and in relation to ONNX.

TF vs. ONNX

- TF 2.1 improves significantly w.r.t 1.6
- Whether TF or ONNX should be used, depends on the batch size and of course on the model itself. The observation is, however, that larger and more complex models should consider using TF.

The tests with ahead-of-time compilation look very promising, but will take more time, so I wouldn't consider them for this PR.

**Comment by Dr15Jones** [comment]
@riga nice work!

File: PhysicsTools/TensorFlow/interface/TBBThreadPool.h [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+
+    explicit TBBThreadPool(int nThreads = -1) : nThreads_(nThreads), numScheduleCalled_(0) {
+      // when nThreads is zero or smaller, use the default value determined by tbb
+      if (nThreads_ <= 0) {
+        nThreads_ = tbb::task_scheduler_init::default_num_threads();
+      }
+    }
+
+    void Schedule(std::function<void()> fn) override {
+      numScheduleCalled_ += 1;
```
Comment (makortel) [inline PhysicsTools/TensorFlow/interface/TBBThreadPool.h]: Given that `TBBThreadPool` (and `NoThreadPool`) are singletons, should `Schedule()` be thread safe?`Or does TensorFlow itself guarantee that `Schedule()` will never be called concurrently even if we're running inference for many models and events concurrently?

**Comment by slava77** [comment]
> Also, I ran some performance tests ([testDeepJetPerformance.cc](https://gist.github.com/riga/5cb64ff74bc1c051b0be77c29df9daab)), based on the deepjet model, to see how the inference time improves from the update to TF 2.1 and in relation to ONNX.

@riga 
Thank you for the tests. These look quite nice.
Is the batch size here related to the number of jets used for inference simultaneously, or is it some variation of the model (not the default currently used in production)?
@hqucms 
please check if the tests match the best what ONNX can do, to the best of your knowledge.
Considering issues on PPC and no direct support for GPU, I have a preference for TF, but I'm not sure I understand all knowns/unknowns just yet.

**Comment by hqucms** [comment]
@slava77 
The tests results from @riga on ONNX are consistent with what I have seen in the past. In fact, @riga and I discussed about this comparison and we both agree that whether which framework is faster depends a lot on the architecture of the DNN model.

> Considering issues on PPC and no direct support for GPU, I have a preference for TF, but I'm not sure I understand all knowns/unknowns just yet.

Just to mention that ONNXRuntime supports also GPU (CUDA & also TensorRT).

**Comment by slava77** [comment]
> Just to mention that ONNXRuntime supports also GPU (CUDA & also TensorRT).

Oh, nice.
I didn't know.
Is it in the version that we distribute with CMSSW now  ("v1.0.0" with whatever extras we add on CMS side)?

**Comment by riga** [comment]
@slava77 
> Thank you for the tests. These look quite nice.
Is the batch size here related to the number of jets used for inference simultaneously, or is it some variation of the model (not the default currently used in production)?

The batch size is related to the number of jets whose discriminants could be inferred in a single inference call. AFAIK this is currently not done yet for DeepJet. The model, however, is exactly the one used in production.

**Comment by hqucms** [comment]
> Is it in the version that we distribute with CMSSW now ("v1.0.0" with whatever extras we add on CMS side)?
@slava77 It's in v1.0.0 -- currently we build it only w/ CPU support but the GPU support can be turned on by changing the build config.

**Comment by makortel** [comment]
We should probably discuss on the technical details of the GPU support of both TensorFlow and ONNX in some forum (core sw if nothing else) to understand if they require/put any constraints on other GPU work on the same process (among others).

File: PhysicsTools/TensorFlow/interface/TBBThreadPool.h (hunk 1 above)
Comment (riga) [reply PhysicsTools/TensorFlow/interface/TBBThreadPool.h]: I am not entirely sure about this. Under the assumption that tbb doesn't use any internal singletons itself, the only non-local object to protect would be `numScheduleCalled_`, so we could make it atomic.

Comment (makortel) [reply PhysicsTools/TensorFlow/interface/TBBThreadPool.h]: > the only non-local object to protect would be `numScheduleCalled_`, so we could make it atomic.

That's exactly what I was thinking. Then also the function-local statics could be declared `CMS_THREAD_SAFE` to suppress warnings from the static analyzer.

**Comment by smuzaffar** [comment]
@riga , we still have the same runtime error
```
----- Begin Fatal Exception 04-Feb-2020 19:13:35 CET-----------------------
An exception of category 'InvalidRun' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=DeepTauId label='deepTau2017v2p1'
Exception Message:
error while running session: Invalid argument: Session was not created with a graph before Run()!
----- End Fatal Exception -------------------------------------------------
```

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmsdist#5525,cms-externals/tensorflow#6

**Comment by smuzaffar** [comment]
please test
testing the new tensorflow 2.1 build using cms externals. RelVals will fail again with the same error message ( https://github.com/cms-sw/cmssw/pull/28711#issuecomment-582113070 )  though

**Comment by riga** [comment]
@smuzaffar 

> @riga , we still have the same runtime error
> 
> ```
> ----- Begin Fatal Exception 04-Feb-2020 19:13:35 CET-----------------------
> An exception of category 'InvalidRun' occurred while
>    [0] Constructing the EventProcessor
>    [1] Constructing module: class=DeepTauId label='deepTau2017v2p1'
> Exception Message:
> error while running session: Invalid argument: Session was not created with a graph before Run()!
> ----- End Fatal Exception -------------------------------------------------
> ```

The error is thrown in [`DeepTauId::getPartialPredictions`](https://github.com/cms-sw/cmssw/blob/1561a67a8bd0b312c6a550c248e687725de6c0c3/RecoTauTag/RecoTau/plugins/DeepTauId.cc#L1089) because the session is not yet initialized with a graph (as the message suggests). When commenting out the partial predictions, a similar error is thrown at any other session `run()` call.

As far as I see, the graphs are loaded with `mem_mapped` set to `true`, but their `node_size()` is 0. Then, when the graph is added to the session ([`direct_session.cc`](https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/core/common_runtime/direct_session.cc#L401-L412)) with

```python
Status DirectSession::Create(GraphDef&& graph) {
  TF_RETURN_IF_ERROR(init_error_);
  if (graph.node_size() > 0) {
    mutex_lock l(graph_state_lock_);
    if (graph_created_) {
      return errors::AlreadyExists(
          "A Graph has already been created for this session.");
    }
    return ExtendLocked(std::move(graph));
  }
  return Status::OK();
}
```

it is not added at all, `graph_created_ ` remains `false`, and the error above is thrown the first time `run()` is called.

I ran the same workflow (136.8311) on the current master (TF 1.6, protobuf 3.5.2) and the node sizes are > 200 which looks reasonable, so I suspect that memory mapped graphs written with TF 1.6 cannot be opened with 2.1.

@kandrosov @mbluj I am not entirely sure how you created the "core", "inner", and "outer" graph files, but could you perhaps try to rewrite them with TF 2.1 and protobuf 3.8.0 ? One of the files would already be enough to run a quick test.

Also, if you agree, I would like to add a few lines here to throw a verbose error in case the number of nodes is zero.

**Comment by kandrosov** [comment]
@riga can you please check if the code works with these files [1] (use .pb files in the folder split) with `mem_mapped` set to `False` [2]. Those should be the same NNs, but without memory mapping (still created with TF1).
If it doesn't work. Tomorrow I'll try to convert produce them with TF2.1

[1] https://www.dropbox.com/sh/85k5t41dd6jedkl/AABRD2nI1EtVyW7f1XnpbwMYa?dl=0
[2] https://github.com/cms-sw/cmssw/blob/master/RecoTauTag/RecoTau/python/tools/runTauIdMVA.py#L760

**Comment by riga** [comment]
@kandrosov Thanks for the files! I can confirm that the files you uploaded work. The graph node sizes are read correctly (353 for "core", and 201 for "inner" and "outer") and the tests succeed. I guess it is less complex to convert them to the mem mapped versions?

**Comment by riga** [comment]
The last commits add some checks to the graph loading and session creation helpers in the TF interface, which could make debugging easier in the future.

The tests will still fail since the DeepTau models need to be updated for TF 2.1 when memory mapping is still required. I gave @kandrosov and @mbluj permissions to add commits to this PR to make those changes for the tau reco.

FYI: I managed to compile the DeepJet model with TF's ahead-of-time compiler and compared the performance ([see plot above](https://github.com/cms-sw/cmssw/pull/28711#issue-359484555)) which looks pretty superior. I will check with @VinInn and @mverzett as soon as I can to automate the process in a build rule.

File: PhysicsTools/TensorFlow/interface/TBBThreadPool.h [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+    int CurrentThreadId() const override {
+      static std::atomic<int> idCounter{0};
+      thread_local const int id = idCounter++;
+      return id;
+    }
+
+    int GetNumScheduleCalled() { return numScheduleCalled_; }
+
+  private:
+    int nThreads_;
```
Comment (makortel) [inline PhysicsTools/TensorFlow/interface/TBBThreadPool.h]: Practically little impact, but this could be made `const` by initializing with 
```cpp
nThreads_(nThreads > 0 ? nThreads : tbb::task_scheduler_init::default_num_threads())
```
The `const` would make it a tiny bit easier to reason about the thread safety.

Comment (riga) [reply PhysicsTools/TensorFlow/interface/TBBThreadPool.h]: ✔︎

**Comment by silviodonato** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by smuzaffar** [comment]
@jfernan2 , should we also include https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/4 for testing this ?

**Comment by jfernan2** [comment]
please abort
Sorry @smuzaffar you are right.
My apologies

**Comment by smuzaffar** [comment]
test parameters
- pull_requests= cms-sw/cmsdist#5525, cms-data/RecoTauTag-TrainingFiles#4

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@riga @kandrosov, can you please fix this build error
```
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_1_X_2020-02-13-2300/src/PhysicsTools/TensorFlow/interface/TensorFlow.h:23:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_1_X_2020-02-13-2300/src/PhysicsTools/TensorFlow/interface/TBBThreadPool.h:33:19: error: cannot assign to non-static data member 'nThreads_' with const-qualified type 'const int'
        nThreads_ = tbb::task_scheduler_init::default_num_threads();
        ~~~~~~~~~ ^
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_1_X_2020-02-13-2300/src/PhysicsTools/TensorFlow/interface/TBBThreadPool.h:73:15: note: non-static data member 'nThreads_' declared const here
    const int nThreads_;
    ~~~~~~~~~~^~~~~~~~~

```

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test
update Keras to version 2.3.1 which should work with TF 2.1 and should fix the failing unit test

**Comment by smuzaffar** [comment]
unit test failure has nothing to do with this update. Can we move forward with this update?

**Comment by perrotta** [comment]
> unit test failure has nothing to do with this update. Can we move forward with this update?

I'll get back on it starting from tomorrow
Please @smuzaffar report here if there is any given deadline that we should aim to for ending the review

**Comment by smuzaffar** [comment]
@perrotta , there is no dead line, take your time. As I will be away for couple of weeks (starting from next week) so I wanted that if we can get it in in my presence then I can take care of non-production IBs (GCC 9, Python3 etc.). But there is no hurry. 

I have run full runTheMatrix and nothing failed, all workflow ran properly.

**Comment by smuzaffar** [comment]
by the way, unit tests failure are due to forntier  , we have seen these failing for 10.6.X PRs too ( https://github.com/cms-sw/cmsdist/pull/5551#issuecomment-587475280 )

**Comment by perrotta** [comment]
+1
- Changes reflect the upstream move from TF1.6 to TF2.1
- Simplifications from the original implementation were implemented following the review here and the discussion at the [reco meeting of Jan 24](https://indico.cern.ch/event/881080/contributions/3711768/attachments/1975491/3287851/2020-01-24_rieger_tf20.pdf): they will allow more simple and modular cmssw updates following future updates of the upstream code
- Performance improvement wrt to previous TF version have been reported in this guthub thread, see https://github.com/cms-sw/cmssw/pull/28711#issuecomment-581931722
- Jenkins tests pass with no differences
- Errors showing up in a few addOn tests are not related to this PR, see https://github.com/cms-sw/cmssw/pull/28711#issuecomment-587551343 
- This PR also adds a set of tools to be used in TensorFlow sessions, as well as a new test script with ahead-of-time compilation

**Comment by perrotta** [comment]
Externals needed to be merged together: cms-sw/cmsdist#5525, cms-externals/tensorflow#6

**Comment by mrodozov** [comment]
@perrotta I'll take care of that once the cmssw PR is signed and merged

**Comment by jfernan2** [comment]
+dqm
No changes seen

**Comment by perrotta** [comment]
@santocch can you please have a look, and sign if you think so?

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1
