### PR TITLE
Fix non-compiling code triggered by EDM_ML_DEBUG flag

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR addresses the failures discussed in #29250 . In several cases the fix looks obvious, in others I have done what looked to me a reasonable choice. I have the feeling that most of this code was not really tested (otherwise people would notice the problems) and it is unused since long time.

#### PR validation:

```USER_CXXFLAGS="-g -D=EDM_ML_DEBUG" scram b --reset``` runs successfully.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
No more compilation errors reported in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f44deb/5352/llvm-analysis/runStaticChecks.log

**Comment by fabiocos** [comment]
@silviodonato I see similar DQM test failures on other recent PRs, I do not see what in this one could cause them (it affects statements that are not normally even compiled), do you confirm? It looks like the problem reported by you in #29237 right?

**Comment by silviodonato** [comment]
@fabiocos yes, the failures are related to #29237

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical fixes
- Jenkins tests pass

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@christopheralanwest @tlampen @ggovi @kpedro88 comments or suggestions?

**Comment by kpedro88** [comment]
+upgrade
thanks for fixing these!

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi the update to CondFormats looks trivial, as the removed variable is not even declared, likely a left-over of some very old development.

**Comment by silviodonato** [comment]
merge
@ggovi `nRecHitsUsedEdge_` is not even defined in SiPixelUtils
