### PR TITLE
Use Modifier.toReplaceWith() in TrackValidation_cff

### PR DESCRIPTION
**Pull request by makortel**
Purely technical change to adapt the phase1 customizations introduced in #13172 with to use `Modifier.toReplaceWith()` introduced in #13198.

Tested in 800pre6, no changes expected.

@rovere @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
@Dr15Jones You might also be interested.

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
Thanks. I appreciate getting rid the of my early hack and replacing it with the cleaner alternative.

**Comment by makortel** [comment]
Whoops, should have checked the "run2" matrix as well. I think the problem is in missing `isChosen()` check in #13198, and I see @Dr15Jones has already a fix in #13220.

**Comment by makortel** [comment]
#13220 got merged in CMSSW_8_0_X_2016-02-09-2300, and as also discussed in #13224, some workflows (e.g. 5.1) fail in step1 with
```
Traceback (most recent call last):
...
  File ".../CMSSW_8_0_X_2016-02-09-2300/python/Validation/RecoTrack/TrackValidation_cff.py", line 497, in <module>
    eras.fastSim.toModify(tracksValidationSeedSelectorsTrackingOnly, _seq = _fastSimTracksValidationSeedSelectorsTrackingOnly._seq)
  File ".../CMSSW_8_0_X_2016-02-09-2300/python/FWCore/ParameterSet/Config.py", line 1183, in toModify
    temp(obj)
  File ".../CMSSW_8_0_X_2016-02-09-2300/python/FWCore/ParameterSet/Config.py", line 1113, in __call__
    _modifyParametersFromDict(params, self.__args, self._raiseUnknownKey)
  File ".../CMSSW_8_0_X_2016-02-09-2300/python/FWCore/ParameterSet/Mixins.py", line 634, in _modifyParametersFromDict
    params[key].setValue(value)
AttributeError: '_SequenceCollection' object has no attribute 'setValue'
```
This PR removes the "offending" code in `TrackValidation_cff.py` and I was able to run e.g. 5.1 with CMSSW_8_0_X_2016-02-09-2300 plus this PR.

**Comment by smuzaffar** [comment]
cmsbuild, please test

**Comment by makortel** [comment]
I should maybe note explicitly that this PR does not fix the other problem discussed in #13224 (affecting e.g. 140.2).

**Comment by makortel** [comment]
The remaining problems are the ones likely caused by #13224.

**Comment by smuzaffar** [comment]
hold
I think this might need an updated #13224 to go in first

**Comment by makortel** [comment]
@smuzaffar This PR should depend only the functionality added in #13220, i.e. it should be independent of #13224.

**Comment by smuzaffar** [comment]
@makortel , so this means that even though we have reverted #13224 for 11h00 IBs, we will still have errors because #13216 is not in yet merged along with #13220 ....right?

**Comment by makortel** [comment]
@smuzaffar Yes, I think that's exactly what should happen.

**Comment by smuzaffar** [comment]
cmsbuild, please test
I will update the test to run it based on CMSSW_8_0_X_2016-02-09-2300 IB and additional PR #13235 (which reverted #13224)

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 This needs to be merged in before my fix to #13224 can be added.

**Comment by davidlange6** [comment]
ok- but lets not get these as small dependent pieces next time around..

**Comment by Dr15Jones** [comment]
Agreed. It was unfortunate that our choice of pull request tests didn't catch this particular problem :(.

**Comment by Dr15Jones** [comment]
The unit test failure is not caused by this pull request. I ran the same test using a vanilla CMSSW_8_0_X_2016-02-09-2300 build and it failed there as well.
