### PR TITLE
Fix build failure in DBG_X

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Log file: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc11/CMSSW_13_1_DBG_X_2023-03-23-2300/Geometry/HGCalCommonData

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc: In static member function 'static std::vector<std::pair<double, double> > HGCalWaferMask::waferXY(int, int, int, double, double, double, double)':
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1245:118: error: expected ';' before ')' token
  1245 |       edm::LogVerbatim("HGCalGeom") << k << ":" << np[orient][k] << ":" << dx[np[orient][k]] + offsetx[np[orient][k]])<< ":"
      |                                                                                                                      ^
      |                                                                                                                      ;
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1256:118: error: expected ';' before ')' token
  1256 |       edm::LogVerbatim("HGCalGeom") << k << ":" << np[orient][k] << ":" << dx[np[orient][k]] + offsetx[np[orient][k]])<< ":"
      |                                                                                                                      ^
      |                                                                                                                      ;
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1266:118: error: expected ';' before ')' token
  1266 |       edm::LogVerbatim("HGCalGeom") << k << ":" << np[orient][k] << ":" << dx[np[orient][k]] + offsetx[np[orient][k]])<< ":"
      |                                                                                                                      ^
      |                                                                                                                      ;
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1281:118: error: expected ';' before ')' token
  1281 |       edm::LogVerbatim("HGCalGeom") << k << ":" << np[orient][k] << ":" << dx[np[orient][k]] + offsetx[np[orient][k]])<< ":"
      |                                                                                                                      ^
      |                                                                                                                      ;
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1296:118: error: expected ';' before ')' token
  1296 |       edm::LogVerbatim("HGCalGeom") << k << ":" << np[orient][k] << ":" << dx[np[orient][k]] + offsetx[np[orient][k]])<< ":"
      |                                                                                                                      ^
      |                                                                                                                      ;
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1311:118: error: expected ';' before ')' token
  1311 |       edm::LogVerbatim("HGCalGeom") << k << ":" << np[orient][k] << ":" << dx[np[orient][k]] + offsetx[np[orient][k]])<< ":"
      |                                                                                                                      ^
      |                                                                                                                      ;
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1326:118: error: expected ';' before ')' token
  1326 |       edm::LogVerbatim("HGCalGeom") << k << ":" << np[orient][k] << ":" << dx[np[orient][k]] + offsetx[np[orient][k]])<< ":"
      |                                                                                                                      ^
      |                                                                                                                      ;
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1341:118: error: expected ';' before ')' token
  1341 |       edm::LogVerbatim("HGCalGeom") << k << ":" << np[orient][k] << ":" << dx[np[orient][k]] + offsetx[np[orient][k]])<< ":"
      |                                                                                                                      ^
      |                                                                                                                      ;
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/05d62365f17d9d2cecbb9853ed8b8cf3/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-23-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:1356:118: error: expected ';' before ')' token
  1356 |       edm::LogVerbatim("HGCalGeom") << k << ":" << np[orient][k] << ":" << dx[np[orient][k]] + offsetx[np[orient][k]])<< ":"
      |                                                                                                                      ^
      |                                                                                                                      ;
  gmake: *** [tmp/el8_amd64_gcc11/src/Geometry/HGCalCommonData/src/GeometryHGCalCommonData/HGCalWaferMask.cc.o] Error 1
```

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
type bug-fix

**Comment by smuzaffar** [comment]
this was introduced in https://github.com/cms-sw/cmssw/pull/41048 and "Static Check" were failed https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6c34ee/31266/summary.html . I think bot should mark PR tests as failed if "Static checks" failed to build

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@AdrianoDee, @srimanob, please, sign this very technical fix.

**Comment by AdrianoDee** [comment]
+upgrade
(pretty technical)
