### PR TITLE
[94X] [L1T] [DQM] LogError -> LogWarning for invalid collections 

### PR DESCRIPTION
**Pull request by kreczko**
Fixing issue https://its.cern.ch/jira/browse/CMSLITDPG-305,
changing all edm::LogError logs for invalid collections to edm::LogWarning

Backport of #21392

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
backport of #21392

**Comment by kreczko** [comment]
@thomreis is cmsbuild bot case-sensitive or does the backport command require special permissions?

**Comment by thomreis** [comment]
It is not case sensitive but it needs to be at the beginning of a comment as far as I know.

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by kreczko** [comment]
The PR is failing due to 
```
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02502/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_X_2017-12-10-0000/bin/slc6_amd64_gcc630/cmsDriver.py", line 55, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02502/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_4_X_2017-12-10-0000/bin/slc6_amd64_gcc630/cmsDriver.py", line 27, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/nweek-02502/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-13-1100/python/Configuration/Applications/ConfigBuilder.py", line 2090, in prepare
    self.addStandardSequences()
  File "/cvmfs/cms-ib.cern.ch/nweek-02502/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-13-1100/python/Configuration/Applications/ConfigBuilder.py", line 746, in addStandardSequences
    getattr(self,"prepare_"+stepName)(sequence = '+'.join(stepSpec))
  File "/cvmfs/cms-ib.cern.ch/nweek-02502/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-13-1100/python/Configuration/Applications/ConfigBuilder.py", line 1962, in prepare_DQM
    self.loadDefaultOrSpecifiedCFF(sequence,self.DQMOFFLINEDefaultCFF)
  File "/cvmfs/cms-ib.cern.ch/nweek-02502/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-13-1100/python/Configuration/Applications/ConfigBuilder.py", line 1191, in loadDefaultOrSpecifiedCFF
    l=self.loadAndRemember(defaultCFF)
  File "/cvmfs/cms-ib.cern.ch/nweek-02502/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-13-1100/python/Configuration/Applications/ConfigBuilder.py", line 321, in loadAndRemember
    self.process.load(includeFile)
  File "/cvmfs/cms-ib.cern.ch/nweek-02502/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2017-12-13-1100/python/FWCore/ParameterSet/Config.py", line 582, in load
    module = __import__(moduleName)
  File "/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-12-13-1100/python/DQMOffline/Configuration/DQMOffline_cff.py", line 19, in <module>
    from DQMOffline.L1Trigger.L1TriggerDqmOffline_cff import *
  File "/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-12-13-1100/python/DQMOffline/L1Trigger/L1TriggerDqmOffline_cff.py", line 284, in <module>
    from DQMOffline.L1Trigger.L1TriggerDqmOffline_SecondStep_cff import *
  File "/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-12-13-1100/python/DQMOffline/L1Trigger/L1TriggerDqmOffline_SecondStep_cff.py", line 3, in <module>
    from DQMOffline.L1Trigger.L1TStage2CaloLayer2Efficiency_cfi import *
  File "/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-12-13-1100/python/DQMOffline/L1Trigger/L1TStage2CaloLayer2Efficiency_cfi.py", line 57, in <module>
    variables_HI['jet'] = L1TStep1.jetEfficiencyThresholds_HI
AttributeError: 'module' object has no attribute 'jetEfficiencyThresholds_HI'
```
See https://github.com/cms-sw/cmssw/blob/848532cb109e1256289e26910b78bd196608c5f6/DQMOffline/L1Trigger/python/L1TStage2CaloLayer2Efficiency_cfi.py#L52
which refers to
https://github.com/cms-sw/cmssw/blob/848532cb109e1256289e26910b78bd196608c5f6/DQMOffline/L1Trigger/python/L1TStage2CaloLayer2Offline_cfi.py#L82

Both changes have been introduced in https://github.com/cms-sw/cmssw/pull/21228.
There is a backport for 92X, but not for 94X. I guess it was merged into master too late for 94X.

However, it seems that I've partially introduced them after the rebase. Apologies, will undo.

**Comment by kreczko** [comment]
I've now removed the code that was accidentally included, tests should now work.

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
Hi @kreczko 
The DQM has moved to 10_0_X. This PR can be closed.

**Comment by thomreis** [comment]
Hi @kreczko 
Since the DQM is not going to use 9_4 release anymore this PR can be closed.

**Comment by fabiocos** [comment]
@thomreis thank you for checking, I close this PR
