### PR TITLE
Fix ODR problems and includes in Selections.h

### PR DESCRIPTION
**Pull request by Teemperor**
We include MessageLogger.h because we use edm::LogVerbatim in this
header and this way it can compile on its own.

We renamed Selection to FilterSelection because we already have
a Selection class in CommonTools/Utils/interface/Selection.h,
which is breaking the One Definition Rule and breaks the C++
modules builds (and can also break the normal CMSSW builds).

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by davidlange6** [comment]
please test

**Comment by Teemperor** [comment]
Fixed compilation errors.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge
